steps:
  builder-image:
    when: Dockerfile
    image: buildx
    settings: "..."

  build-jar:
    image: gitea.simcop2387.info/simcop2387/openjdk-17-builder:latest
    commands:
      - ls -lah
      - mvn install
  publish-github:
    image: ...
    files:
      - target/UltimateCards-*-original.jar

